# Generated by Django 4.2.4 on 2023-09-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTorneos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenadores',
            name='club',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='club',
        ),
    ]
